[package]
name = "module-worker"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-convert = { path = "../../../../lib/convert" }
chirp-client = { path = "../../../../lib/chirp/client" }
chirp-worker = { path = "../../../../lib/chirp/worker" }
chrono = "0.4"
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
util-module = { package = "rivet-util-module", path = "../util" }

module-version-get = { path = "../ops/version-get" }
module-instance-get = { path = "../ops/instance-get" }
module-game-version-get = { path = "../ops/game-version-get" }

[dependencies.sqlx]
version = "0.6"
default-features = false
features = [
	"runtime-tokio-native-tls",
	"postgres",
	"macros",
	"uuid",
	"json",
	"tls",
]

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }

chat-thread-get-or-create-for-topic = { path = "../../chat-thread/ops/get-or-create-for-topic" }
faker-game = { path = "../../faker/ops/game" }
faker-game-version = { path = "../../faker/ops/game-version" }
upload-get = { path = "../../upload/ops/get" }
upload-prepare = { path = "../../upload/ops/prepare" }

