name: rust

on:
  - pull_request

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # Enable fail-fast behavior
    shell: bash

jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: cargo deny (svc)
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --manifest-path svc/Cargo.toml
      - name: cargy deny (lib/bolt)
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --manifest-path lib/bolt/Cargo.toml
